import argparse


parser = argparse.ArgumentParser()
parser.add_argument('--seed', type=int, default=4171)
parser.add_argument('--hyper_prd', type=int, default=1024)
parser.add_argument('--slot_num', type=int, default=64)
parser.add_argument('--node_num', type=int, default=[8, 10, 12, 14, 16, 18, 20])
parser.add_argument('--buff_size', type=int, default=1e6)
parser.add_argument('--flow_prd', type=int, default=[2, 4, 8, 16, 32, 64])
parser.add_argument('--flow_len', type=int, default=[64, 1518])
parser.add_argument('--flow_dly', type=int, default=[32768, 65536])
parser.add_argument('--x_dim', type=int, default=4)
parser.add_argument('--e_dim', type=int, default=1)
parser.add_argument('--p_dim', type=int, default=2)
parser.add_argument('--agn_hidden_dim', type=int, default=300)
parser.add_argument('--layer_num', type=int, default=20)
parser.add_argument('--prd_hidden_dim', type=int, default=[64, 128, 256])
parser.add_argument('--r_lr', type=float, default=1e-5)
parser.add_argument('--s_lr', type=float, default=1e-4)
parser.add_argument('--weight_dec', type=float, default=1e-4)
parser.add_argument('--update_step', type=int, default=100)
parser.add_argument('--batch_size', type=int, default=64)
parser.add_argument('--gamma', type=float, default=0.9)
parser.add_argument('--episodes', type=int, default=500)
parser.add_argument('--val_times', type=int, default=10)
parser.add_argument('--train_flow_num', type=int, default=1000)
parser.add_argument('--val_flow_num', type=int, default=10000)
parser.add_argument('--failure_step', type=int, default=500)

args = parser.parse_args()